// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD08MTRJOu1z-D34ZOOo4yVnKJh0zAEcQU',
    appId: '1:315696578097:android:384d6fe80dbc9c45979f10',
    messagingSenderId: '315696578097',
    projectId: 'test-chat-app-da2ad',
    storageBucket: 'test-chat-app-da2ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeRMvzsibc1-1OSz0a9aupGwonx9xZXWs',
    appId: '1:315696578097:ios:cd9f6413b89bf6c2979f10',
    messagingSenderId: '315696578097',
    projectId: 'test-chat-app-da2ad',
    storageBucket: 'test-chat-app-da2ad.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeRMvzsibc1-1OSz0a9aupGwonx9xZXWs',
    appId: '1:315696578097:ios:cd9f6413b89bf6c2979f10',
    messagingSenderId: '315696578097',
    projectId: 'test-chat-app-da2ad',
    storageBucket: 'test-chat-app-da2ad.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoj5CsJDtpKfJafz1Flgh2e_gHzHe8Tao',
    appId: '1:315696578097:web:aa2ded32df1f220d979f10',
    messagingSenderId: '315696578097',
    projectId: 'test-chat-app-da2ad',
    authDomain: 'test-chat-app-da2ad.firebaseapp.com',
    storageBucket: 'test-chat-app-da2ad.firebasestorage.app',
  );
}
